version: "3"

services:
  dialects-io-celery-worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/yijunx/code
      - ~/etc/localtime:/opt/yijunx/etc/localtime
      - ~/etc/timezone:/opt/yijunx/etc/timezone
    command: ["tail -f /dev/null"]
    networks:
      - default

networks:
  default:
    external:
      name: micro-services
